microsoft/VoTT

- src/index.js
- src/public/js/video-tagging/js/canvastools.js
- src/public/js/video-tagging/video-tagging.html
Privary tag display is now responsive to region box size.
Key shortcuts on region level are now in RegionsManager (tab, delete, backspace).
Key shortcuts merged for video and images (back/fwd, duplicate).
Multiple regions selection support (for deletion as of now) - use SHIFT key.
> Responsive tags; Key shortcuts update; multi-selection support

- src/index.js
When the image files have been changed in the same directory, the saved tag will be loaded incorrectly because it is based the index of images in the directory ("videotagging.imagelist"). I have made the change that the array "videotagging.frames" will be transformed into a new array with the image filename as the key and save to a new property "framesByImagesName" in save file.
> Fix to load tags correctly when the image files have been changed in the same directory.

- src/public/js/video-tagging/video-tagging.html
For compatibility coordinates are now stored in two formats:
x1-y2 + width, height -- old format, when width and height are current scaled image size and x1-y2 are relative to that size.
box {x1-y2} - new format for absolute region coorinates based on actual image size
---
Important - it is not fully compatible with previous dev branches, manual data changes might be required.
> Updated file structure for region storage

- src/lib/videotagging_extensions/detection.js
Fix export bug where detection.js was referencing getCurrentFrame function which doesn't exist.
> Fix video export bug

- src/public/html/help-configuration.html
- src/public/js/video-tagging/video-tagging.html
Add shortcut to be able to move between frames using Q and E keys. Used to speed up tagging flow. 
Resolves #326
> Add shortcut to move frames

- src/public/js/video-tagging/css/video-tagging.css
If more tags are added to the tag list than can be displayed, they are simply truncated and are no longer visible. By using the css attribute _overflow-y: auto_, a scrollbar is displayed as soon as the elements within the div exceed the visible area. This also applies if the app window size is reduced and the tags would become unvisible.
closes #320.
> Display a scrollbar for the tags list when not all tags are visible

- .codecov.yml
- .gitignore
- README.md
- azure-pipelines/linux/continuous-build-linux.yml
- codecov.yml
- package.json
1. Modify linux agent test run to upload coverage report to codecov.
1. Enable pr comment so codecov can post back report to PR.
1. Enable commit status so it will block if coverage goes down.
> [AB#16330] Set up codecov support

- .codecov.yml
- .gitignore
otherwise it will use the current coverage of base branch
> set explicit target for patch coverage

- src/providers/export/exportProviderFactory.test.ts
- src/providers/export/exportProviderFactory.ts
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/export/exportForm.test.tsx
- src/react/components/pages/export/exportForm.tsx
- src/react/components/pages/export/exportPage.test.tsx
- Adding default export filter if none is selected (currently first registered filter is set as default)
- Adding test for default export filter
- Fixing test verifying null settings appropriate uses default export
- Fixed a typo of "component" I saw that was super annoying me
> Adding default export filter and updating tests - AB#16446

- src/react/components/pages/projectSettings/projectForm.tsx
Somehow I missed a .properties in finding the default from the schema, will add another test to catch this, but opening PR for this since project settings are likely broken at moment.
> Fixing bug introduced on default video settings

- .gitignore
- README.md
- docs/PLATO.md
- package-lock.json
- package.json
- tsconfig.json
1. update compile target to es6
> add npm script for using plato

- package-lock.json
- package.json
- src/common/mockFactory.ts
- src/models/applicationState.ts
- src/react/components/pages/editorPage/assetPreview.tsx
- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/editorPage/editorSideBar.test.tsx
- src/react/components/pages/editorPage/editorSideBar.tsx
- src/react/components/pages/projectSettings/projectForm.test.tsx
Initial implementation of simple video player on editor page
- Includes video player with customizable playback speed
- Auto plays selected videos
- No longer auto plays videos in side bar
- Supports custom image to display when video not playing (defaults to 1st video frame)
- Updates tests
- Refactors a few other tests to centralize test asset creation
- Updates version of React to 16.7.0
- Rename IVideoSettings to IProjectVideoSettings for clarity
> Adding video player to editor page - AB#16699

- azure-pipelines.yml
in order to test and integrate [greenkeeper](https://greenkeeper.io/) I have to enable CI on branches (right now it's disable).  But I don't want this to run for all branches, so only enable it on greenkeeper-created branches which always starts with `greenkeeper/`
> enable CI for greenkeeper created branches

- src/providers/export/tensorFlowRecords.ts
- src/providers/export/tensorFlowRecords/tensorFlowBuilder.test.ts
- src/providers/export/tensorFlowRecords/tensorFlowBuilder.ts
- src/providers/export/tensorFlowRecords/tensorFlowHelpers.test.ts
- src/providers/export/tensorFlowRecords/tensorFlowHelpers.ts
WIP: Not ready yet for approving
> Separate TFRecords code on different file

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/mockFactory.ts
- src/common/strings.ts
- src/models/applicationState.ts
- src/react/components/pages/editorPage/assetPreview.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- Hook video player into canvas
- Update styles base on pause state to allow tagging of individual frames of video
- Remove video player component from AssetPreview (more simplified)
> Updating Canvas to handle Videos and allow tagging - AB#16580

- package-lock.json
- package.json
- src/providers/export/tensorFlowRecords.ts
- src/providers/export/tensorFlowRecords/tensorFlowHelpers.ts
- src/providers/export/tensorFlowRecords/tensorFlowReader.test.ts
- src/providers/export/tensorFlowRecords/tensorFlowReader.ts
- All TFRecords methods and helpers are now implemented on separated files in the tensorFlowRecords sub-folder
- Both Builder and Reader class support now TFRecords buffer with multiple records in order to eventually export all assets in a single .tfrecord file
- Test generate single and multiple records TFRecords with the Builder class and check validation with the Reader class
> TFRecords Reader and Builder-Reader integration tests

- src/common/mockFactory.ts
- src/models/applicationState.ts
- src/providers/export/azureCustomVision.test.ts
- src/providers/export/tensorFlowPascalVOC.test.ts
- src/providers/export/tensorFlowRecords.test.ts
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/canvasHelpers.test.ts
- src/react/components/pages/editorPage/canvasHelpers.ts
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
Preparatory to cut/copy/paste effort. Trying to make canvas a little easier to work with, but didn't want the PR to be too big. Main changes are:
- Replace `ITagMetadata` with `ITag`
- Break up large functions in canvas to smaller, re-usable functions
> Small refactor of canvas and editor page

- .gitignore
- package.json
- scripts/complexity-analysis.js
- scripts/generate-report.sh
- Moved from `plato` --> `es6-plato`
- Running the tool (either one...) is easier as a script, using the module/API directly
- Added shell script for managing transpilation from TS --> ES6 and running report generation easily from CI
- Should work w/ existing CI scripts; still need to do work to upload this to blob to view history over time
#AB17036
> Added v2 complexity report scripts.

- src/react/components/common/tagsInput/tagsInput.test.tsx
- src/react/components/common/tagsInput/tagsInput.tsx
- Added `data-tag-name` data attribute to set the original tag name/key
- Updated event handling to use `currentTarget` so that the element will always be the same as the element that has the `click` handler.
> Fix bug applying tags when clicking on color bubble AB#16923

- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
When navigating directly to a project edit page via URL, the initial state is invalid, and is not updated when the correct data is retrieved, and this fixes that.
> EditorPage does not have correct state when navigating directly via URL- AB#17079

- src/services/assetService.test.ts
- src/services/assetService.ts
Resolve issue detecting asset type in case the file name contain more dot separator:
- ie file.jpg.tfrecord
> Fix Asset detection from path

- src/common/mockFactory.ts
- src/models/applicationState.ts
- src/providers/export/azureCustomVision.test.ts
- src/providers/export/azureCustomVision.ts
- src/providers/export/tensorFlowPascalVOC.test.ts
- src/providers/export/tensorFlowPascalVOC.ts
- src/providers/export/tensorFlowRecords.test.ts
- src/providers/export/tensorFlowRecords.ts
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/canvasHelpers.test.ts
- src/react/components/pages/editorPage/canvasHelpers.ts
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/services/assetService.test.ts
- src/services/assetService.ts
Updated `IRegion` `tags` to be an `string[]` vs`ITag[]`.
The list of project tags should be the source or truth for tags and all other areas should only reference tags by name.  This ensures that the tag colors always use those referenced directly by the project and not within an region stored data.
> Refactor region tags to only be a string array

- docs/PLATO.md
- package.json
- scripts/complexity-analysis.js
- scripts/generate-report.sh
- scripts/push-report.sh
Complexity CI is _finally_ working end-to-end, retaining history for each merged PR.
- Updated scripts to be more explicit with paths, passing them via command line args
- Added more logging
- Updated docs
Was able to test this e2e by pointing Azure DevOps to my branch.
> Updating report CI scripts to be more robust.

- src/react/components/common/assetPreview/videoAsset.tsx
1. q/e for navigating between tagged frames
1. a/d & left/right-arrow for navigating between non-tagged frames
> [AB#17027] add keyboard shortcut for navigating between video frames

- src/common/mockFactory.ts
- src/react/components/common/assetPreview/assetPreview.tsx
- src/react/components/common/assetPreview/videoAsset.tsx
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/editorPage/editorSideBar.tsx
- src/services/assetService.test.ts
- src/services/assetService.ts
- Fixes bug where editor page was attempting to set the selectedAsset in the sidebar to a non-root asset
- Renamed `parentAsset` to `rootAsset` to make this more clear in event handlers
> Fixes previous/next buttons to navigate between assets

- src/react/components/common/assetPreview/videoAsset.test.tsx
- src/react/components/common/assetPreview/videoAsset.tsx
We're currently running unnecessary code for every video in the side bar by hooking the video state change callback and going through all the logic there. Only hook this callback if autoPlay is true.
> Only hook video state change on non-preview assets AB#17076

- src/react/components/common/assetPreview/assetPreview.test.tsx
- src/react/components/common/keyboardManager/keyboardManager.test.tsx
- src/react/components/common/keyboardManager/keyboardManager.tsx
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/editorPage.test.tsx
Fixes an issue in the `KeyboardManager` component where a configured keyboard accelerator can override behavior when the user is entering data into a input/textarea element leading to a poor user experience.  Disables `KeyboardManager` events from firing when the app detects the user is focus in an input element.
Resolves AB#17120
> fix: Disables KeyboardManager when focused on input elements

- src/react/components/common/filePicker/filePicker.tsx
- src/react/components/pages/homepage/homePage.test.tsx
- src/react/components/pages/homepage/homePage.tsx
The homepage was incorrectly closing any open project. This fix removes the explicit `closeProject` action and allows the user to navigate to the homepage and back to an open project if desired.
Resolves AB#17140
> fix: Navigating to homepage should't close any open project

- src/react/components/pages/homepage/homePage.test.tsx
- src/react/components/pages/homepage/homePage.tsx
- src/react/components/pages/projectSettings/projectForm.test.tsx
- src/react/components/pages/projectSettings/projectForm.tsx
Fixes a bug where when attempting to create a new project after already have opened a project it does not close the existing project before navigating the user to the new project screen. 
Also resolves issue where security token picker component was not rendering in in project settings form.
Resolves AB#17172, AB#17177, AB#17179, AB#17180
> fix:Resolves issue where user is unable to create new project

- src/common/mockFactory.ts
- src/common/utils.ts
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/canvasHelpers.ts
- src/react/components/pages/editorPage/editorPage.test.tsx
Corrects an issue where bounding box position was not being updated correctly when a region was moved within the canvas editor.  Also randomized region test data to ensure we are tests are more accurate
> fix: Correct bounding box values on region move

- CONTRIBUTING.md
Contribution guidelines now reflect new git commit message conventions, to support change log generation.
AB#17149
> docs: update contribution guidelines for changelog

- src/electron/providers/storage/localFileSystem.test.ts
- src/electron/providers/storage/localFileSystem.ts
- src/services/assetService.test.ts
- src/services/assetService.ts
Fixes the issue where the last region in an asset is unable to be deleted.  When all the regions on an asset are deleted the asset transitions back into the "Visited" state.  Therefore, when the asset metadata is saved is is not persisted back to the file system since it is no longer in the "Tagged" state.  The fix is to instead of saving the asset metadata file it should be deleted from the storage provider since the asset metadata file doesn't not provide any additional metadata outside of region data.
Resolves AB#17174
> fix: Fixes issue where regions cannot be deleted

- CHANGELOG.md
- scripts/generate-changelog.sh
- scripts/release-pr.sh
This adds a new script for generating changelogs. Once integrated into CI, it will update `CHANGELOG.md` for new, tagged releases.
The changelog will look like this (generated fomr the current commit history): 
[GitHub Release](https://github.com/Microsoft/VoTT/releases/tag/2.0.0-preview.2)
- ci: add changelog script
- fix:Resolves issue where user is unable to create new project (#601)
- fix: Navigating to homepage should't close any open project (#596)
- feat: Add tag to project while importing TFRecords [AB#17001] (#586)
- fix: Disables KeyboardManager when focused on input elements (#595)
- fix: Corrects canvas sizing and region sizes (#592)
AB#17192
> ci: add changelog script

- src/models/applicationState.ts
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- Save last visited asset id on project save
- Scroll to last visited asset on opening project
- Added unit test to check save and load of last visited asset info
Implement [#AB17139]
> feat: Ability to retain the state of the last viewed asset on project open [#AB17139]

- src/react/components/pages/editorPage/editorPage.tsx
- src/services/projectService.test.ts
- src/services/projectService.ts
Resolves the issue where orphaned asset metadata files still exist on the target connection.
Resolves AB#17101
> fix: Delete asset metadata files when project is deleted

- README.md
- azure-pipelines/linux/continuous-build-linux.yml
also update README to point ADO badge to new CI pipeline
have to create a new pipeline using the new YAML wizard
so that GitHub Pipelines App is used instead of webhook.
This fix the issue where re-running the ADO build from the
`Check` tab in GitHub doesn't kick off actual build in ADO.
> ci: make sure build fail if codecov token is missing

- src/react/components/pages/editorPage/editorPage.tsx
- src/redux/reducers/currentProjectReducer.test.ts
- src/redux/reducers/currentProjectReducer.ts
- src/services/projectService.ts
- Move last visited tag settings from editor Page to project Redux action
- Removed non necessary filter on selecting asset files to delete
Fix bug [#AB17101]
> fix: Move last visited tag settings to reducer to fix delete file assets bug [#AB17101]

- .env
- config/webpack.common.js
- package.json
- src/App.test.tsx
- src/App.tsx
- src/electron/main.ts
- src/react/components/pages/homepage/homePage.test.tsx
- src/react/components/pages/homepage/homePage.tsx
- src/react/components/shell/mainContentRouter.test.tsx
Resolves the issue where user is unable to navigate to new project screen from the homepage.  This also addresses other strange behavior related to routing in the app.
- User being navigated to the homepage after creating a connection
- Refresh application button not working
Resolves AB#17258, 17263, 17058
> fix: Fixes issue where user is unable to navigate to new project screen

- package-lock.json
- src/react/components/common/keyboardManager/keyboardManager.tsx
- src/react/components/common/keyboardManager/keyboardRegistrationManager.ts
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/editorPage/editorToolbar.test.tsx
- src/registerToolbar.ts
This feature aims to make it easier for a user to keep one hand on the keyboard and one on the mouse for more efficient tagging of large quantities of images. Previous Asset (W) and Next Asset (S) already exists. This feature adds hotkeys to the editor toolbar as follows:
- Select (V) (following common hotkey convention)
- Draw Rectangle (R)
- Draw Polygon (P)
- Save Project (Ctrl + S)
- Export Project (Ctrl + E)
In addition, tag hotkeys have been simplified to numbers 1 through 0, instead of Ctrl + 1, etc.
AB#17096
> feat: add hotkeys for all editor toolbar items and simplify tag input hotkeys (remove ctrl+)

- src/providers/storage/azureBlobStorage.ts
- src/services/assetService.ts
When a asset is in the visited state, the app attempts to delete the asset metadata file to prevent an explosion of files in the event an asset transitions from tagged back to visited.  This adds protections around the call to the storage provider to catch any unhandled delete failures.
> fix: Fixes issue where calls to deleted non existent blobs causes editor issues

- src/providers/export/exportProviderFactory.ts
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/registerToolbar.ts
fix: re-add exportProject to registerToolbar
ExportProject interface had been removed from the registerToolbar file, causing no action when the "export project" button was clicked. Adding this interface to the file will allow for projects to be exported.
Helps support multiple bug fixes
> fix: re-add exportProject to registerToolbar

- package-lock.json
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/mockFactory.ts
- src/common/strings.ts
- src/providers/export/tensorFlowPascalVOC.test.ts
- src/react/components/pages/projectSettings/projectMetrics.test.tsx
- src/react/components/pages/projectSettings/projectMetrics.tsx
- src/react/components/pages/projectSettings/projectSettingsPage.scss
- src/react/components/pages/projectSettings/projectSettingsPage.test.tsx
- src/react/components/pages/projectSettings/projectSettingsPage.tsx
add a panel inside `Project Settings` page to display relevant project metrics:
1.  number of source assets 
1.  number of tagged assets
1.  number of visited assets
1.  number of regions drawn
1. avg tags per asset
1. number of tags categories in project
1. number of tags in each category
AB#16587
> feature: display project metrics

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/models/applicationState.ts
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/canvasHelpers.test.ts
- src/react/components/pages/editorPage/canvasHelpers.ts
- Still need to implement tests for most of this
- Scales pasted regions appropriately
- Pastes regions that don't fit to top left and cascades down and to the right
- Throws error if region is too big to be pasted in asset
> fix: Don't allow invalid pasting [AB#17353]

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/canvasHelpers.test.ts
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/registerToolbar.ts
- Clear regions now has a confirmation modal before actually performing the action
- Ctrl+Delete now triggers the confirmation modal
- Icon for clearing regions is now the Ghostbuster's "ban" icon
> feat: Clear Regions updates [AB#17269]

- src/models/applicationState.ts
- src/providers/export/azureCustomVision.json
- src/providers/export/tensorFlowPascalVOC.json
- src/providers/export/tensorFlowRecords.json
- src/providers/export/vottJson.json
- src/react/components/pages/export/exportForm.test.tsx
- src/react/components/pages/export/exportForm.tsx
- src/react/components/pages/export/exportPage.tsx
"all assets" doesn't currently export all assets,
removing it so it doesn't cause confusion.
We will add back this support once we have a working fix.
AB#17461
> fix: remove "All assets" from export options dropdown

- src/common/mockFactory.ts
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/canvasHelpers.ts
This handles an error where we set a guard to prevent non-null tags when getting the TagsDescriptor. CanvasTools expects a `null` when creating a region with no tags, so it's fine to just return null if there are no tags rather than raising an exception.
Resolves [AB#17357]
> fix: Handle project with no tags while loading regions [AB#17357]

- package.json
- public/index.html
- scripts/deploy-to-azure.sh
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/index.scss
- src/react/components/pages/appSettings/appSettingsPage.tsx
Script to push VoTT single page app to Azure as a static Web site.
Display version/commit SHA in multiple places to be able to easily
determine version.
[AB#17484](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=17484)
Preview deployment available here: https://vottdev.z5.web.core.windows.net
> ci: script to deploy VoTT to Azure

- src/react/components/pages/editorPage/editorPage.tsx
- save asset metadata for all valid asset type
Fix [AB#17538]
> fix: save asset metadata for all valid asset type [AB#17538]

- src/redux/actions/applicationActions.ts
fix misspelling in applicationActions.ts from "dipatch" to "dispatch"
> fix: misspelling in applicationActions.ts [AB#17157]

- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/editorPage.tsx
Resolves issue where if tag color is modified while in the editor page, the color changes are not applied till you reload or navigate away from the current asset
Resolves AB#17264
> fix: Re-apply tags in editor when project tags are updated

- src/redux/actions/projectActions.test.ts
- src/redux/actions/projectActions.ts
create empty tags array on project creation if no tags created,
right now it's null
AB#17588
> fix: metrics page throw error if project has no tags

- src/index.scss
Fixes style that hides Submit button in forms using react-jsonschema-form
> fix: Remove height from root style [AB#17672]

- .editorconfig
- azure-pipelines/web/generate-web-artifact.yml
- scripts/generate-web-artifact.sh
1. move deploy functionality to release
1. replace `az storage` command with `az copy` ADO task
Examples:
[Build](https://dev.azure.com/msft-vott/VoTT/_build/results?buildId=1930&view=logs)
[Release](https://dev.azure.com/msft-vott/VoTT/_releaseProgress?_a=release-environment-logs&releaseId=161&environmentId=161)
[AB#17779](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=17779)
> ci: refactor web deploy pipeline

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/providers/export/vottJson.json
- src/providers/export/vottJson.test.ts
- src/providers/export/vottJson.ts
- src/providers/export/vottJson.ui.json
- src/react/components/pages/export/exportForm.test.tsx
Adds option that allows the user to specify whether or not binary images assets will be generated as part of the JSON export provider
Resolves [AB#18068](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=18068)
> feat: Adds option to specify if images are included with JSON export

- src/common/hostProcess.ts
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/react/components/pages/connections/connectionForm.test.tsx
- src/react/components/pages/connections/connectionForm.tsx
Error message displays when adding a Bing Image Search asset provider
type. This is only applicable for the Browser target.
[AB#17153](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=17153)
> fix: CORS warning message for Bing Image Search

- src/common/layout.test.tsx
- src/common/layout.ts
- src/react/components/common/assetPreview/assetPreview.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/editorPage.scss
Normalizes the display of both image and video assets in VoTT.  `<video>` tags by default display with `object-fit: contain` which forces the video to always render in its correct aspect ratio.  The browser will automatically add horizontal / vertical bars as necessary based on fluid layouts.  This updates images to also use this same technique to preserve aspect ratio.  
The side effect however is having to manually calculate the actual asset content from within the HTML elements by detecting aspect ratio and computing correct offsets.
> feat: Auto-size video/image assets and position canvas

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/react/components/common/assetPreview/assetPreview.test.tsx
- src/react/components/common/assetPreview/assetPreview.tsx
- src/react/components/common/assetPreview/videoAsset.test.tsx
- src/react/components/common/assetPreview/videoAsset.tsx
- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/editorPage/editorSideBar.tsx
Enforces that there are no untagged regions within an asset before navigating away from the current loaded asset.  Displays an alert warning when user attempt to navigate.
Resolved [AB#18070](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=18070)
> feat: Enforce asset tagging before switching assets

- package.json
- src/react/components/pages/projectSettings/projectForm.json
Regex now prevents invalid path characters (<>"/\\|?*) in project
names, since it is used in file system operations. Using reserved
characters for Windows, as it is a superset of OSX/Linux.
[AB#18204](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=18204)
> fix: don't allow invalid path characters in project name

- src/react/components/common/keyboardBinding/keyboardBinding.test.tsx
- src/react/components/common/keyboardManager/keyboardManager.test.tsx
- src/react/components/common/keyboardManager/keyboardManager.tsx
- src/react/components/common/keyboardManager/keyboardRegistrationManager.test.ts
- src/react/components/common/keyboardManager/keyboardRegistrationManager.ts
- src/react/components/common/tagInput/tagInputItem.tsx
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/shell/helpMenu.tsx
- src/react/components/toolbar/toolbarItem.test.tsx
- src/registerToolbar.ts
Resolves an issue where normal Cmd+ keyboard shortcuts that typically work on Mac OSX don't work in VoTT.  The fix treats Ctrl or Cmd to be equivalent and also checks the value of the "meta" key within keyboard events.
Resolves [AB#18159](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=18159)
> fix: Updated keyboard manager to support meta (aka cmd) key

- src/react/components/pages/editorPage/editorPage.scss
A regression was introduced that caused the video timeline overlay to override the z-index of the player bar causing the player controls to not work as expected.  This resolves the issue by adjusting the z-index of both the player container as well as the disabled overlay for when controls are disabled.
Resolved [AB#18202](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=18202)
> fix: Adjusts z-index video player overlays

- README.md
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/mockFactory.ts
- src/common/utils.test.ts
- src/common/utils.ts
- src/models/v1Models.ts
- src/providers/export/azureCustomVision.test.ts
- src/react/components/pages/homepage/homePage.test.tsx
- src/react/components/pages/homepage/homePage.tsx
- src/services/assetService.test.ts
- src/services/assetService.ts
- src/services/importService.test.tsx
- src/services/importService.ts
Adds ability to import V1 video projects
> feat: add ability to import v1 video project

- src/react/components/pages/projectSettings/projectForm.test.tsx
- src/react/components/pages/projectSettings/projectForm.tsx
- src/react/components/pages/projectSettings/projectSettingsPage.test.tsx
- src/react/components/pages/projectSettings/projectSettingsPage.tsx
This adds functionality to persist partial project information when creating a new project.  Right now when creating a new connection inline within the create project flow and returning to the create project screen your partial project information is lost.  Partial form progress is now saved into local storage and bound when returning to the form.
Resolves #758
> feat: Save partial project progress during project creation

- CHANGELOG.md
- README.md
Minor updates and corrections to the main readme and changelog.
> docs: updates to readme and changelog

- src/react/components/common/colorPicker.tsx
- src/react/components/common/tagInput/tagInput.test.tsx
- src/react/components/common/tagInput/tagInput.tsx
- Updates the `TagInput` component to use the `TagInputItem` type instead of `RefObject<TagInputItem>`
- Adds several unit tests of uncovered areas for `TagInput`
> fix: Fix display of tag color picker

- src/electron/providers/storage/localFileSystem.test.ts
- src/electron/providers/storage/localFileSystem.ts
Fix #776 
String.length is not appropriate for calculating buffer size when non-alphabet letter is included in content.
Change the method Buffer.alloc to Buffer.from as directed by the nodejs document.
> fix: change method for alloc string to buffer

- src/services/projectService.test.ts
- src/services/projectService.ts
When loading a v2.0.0 project that was configured to use `tensorflowPascalVOC` export provider it fails on project load and get stuck in an infinite loop
**Fix**
Adds a check during project load to update the export options if project was using previous pascalVOC name.
> fix: Update export options for pascalVOC rename

- src/providers/export/cntk.ts
- src/services/projectService.ts
Fixes an issue where the images exported out of a video file were missing file extension for video projects.
> fix: CNTK export images bug fix

- src/common/htmlFileReader.ts
Retargeted. See https://github.com/microsoft/VoTT/pull/801.
Closes https://github.com/microsoft/VoTT/pull/801.
Closes https://github.com/microsoft/VoTT/issues/838.
> fix: Use image/jpeg as MIME type for canvas.toBlob

- src/App.test.tsx
- src/setupTests.js
Create `window.require` function in tests that returns an electron object
Resolves #849
> fix: Resolve UnhandledPromiseRejection in test

- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/editorPage/editorSideBar.test.tsx
- src/react/components/pages/editorPage/editorSideBar.tsx
feat: change sidebar from vertical to horizontal
Moved the vertical asset previewer to be horizontal and at the bottom of the screen. This helps maximize the size of the picture being tagged when it is a landscape photo.
AB#860
> feat: move asset preview to horizontal

- src/providers/export/cntk.test.ts
- src/providers/export/cntk.ts
- src/providers/export/pascalVOC.test.ts
- src/providers/export/pascalVOC.ts
- src/providers/export/testAssetsSplitHelper.test.ts
- src/providers/export/testAssetsSplitHelper.ts
The test asset may not included all tags when export with test/train split option and uneven distribution of tags in current venison (2.1.0). Here is an example:
Image 1-8 are tagged with Tag-1.
Image 9-10 are tagged with Tag-2.
Export provider: PascalVOC
Asset State: Only tagged Assets
Test / Train Split is 80%.
Output
tag-1_val.txt
```
asset-9.jpg -1
asset-10.jpg -1
```
tag-2_val.txt
```
asset-9.jpg 1
asset-10.jpg 1
```
In current venison, there is no images of tag "Tag-1" in the text file "tag-1_val.txt" because the split method is based on the whole image set so only image 9 & 10 are put in test asset. The split method is changed to extract the test assets by each tag and combine them at the end. Image 7,8,10 will put in test asset after the change applied. 
Output
tag-1_val.txt
``` …
```
> fix: test asset distribution to include all tags on test/train split

- src/react/components/common/connectionPicker/connectionPicker.tsx
Previously, in project settings, a user could only see the display name of the source and target connections, which might not have made clear which directory or storage account they were using. This adds the filepath or storageaccount and container name the to project settings dropdowns for source and target connection.
Resolves #792
Before:
After:
> feat: add preview of filepaths in project settings

- README.md
After the storage account was deleted, I had to manually re-create the static web page. Unfortunately, the links are generated by Azure and I cannot configure it to be exactly the same link as it was before. This updates the links in the README so that people can access the web app
> fix: Update new link for VoTT site

- README.md
- src/common/localization/ja.ts
- src/common/strings.test.ts
- src/common/strings.ts
Japanese translation verified by @aykhara and other native Japanese speakers
> feat: Japanese language support

- src/common/localization/zh-tw.ts
- src/common/strings.test.ts
- src/common/strings.ts
Traditional Chinese translation verified by @rextangtw
> feat: Traditional Chinese language support

- package-lock.json
- package.json
The current version of node-sass is very outdated which is causing build errors due to 404 not found requests to components no longer available.
This PR updates to latest version of node sass and confirms local development can be setup.
> fix: Updates node-sass version to support local development

- README.md
- docs/RELEASE_GUIDE.md
* added release process section into readme
* updated RELEASE_GUIDE.md accordingly
> docs: update release guide doc

- src/providers/export/azureCustomVision.test.ts
- src/providers/export/azureCustomVision.ts
- src/providers/export/azureCustomVision.ui.json
- src/providers/export/azureCustomVision/azureCustomVisionService.test.ts
Azure Custom Vision REST API endpoint was updated and the old one was deprecated. Updating to current version
> Fix: Update custom vision url

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/localization/ja.ts
- src/common/localization/ko-kr.ts
- src/common/localization/zh-ch.ts
- src/common/localization/zh-tw.ts
- src/common/strings.ts
- src/providers/storage/bingImageSearch.json
- src/providers/storage/bingImageSearch.test.ts
- src/providers/storage/bingImageSearch.ts
The `Bing Search` resource is undergoing a transition from a `Cognitive Service` to the `Azure Marketplace`.  During this transition it is possible to have bing search resources that use different endpoint urls.
This fix introduces a new `endpoint` textbox that defaults to the new default resource url (https://api.bing.microsoft.com/).  However, for users with older resources that have not specified the field it will fall back to the older cognitive services url ( https://api.cognitive.microsoft.com/bing).
In addition to the fix this also introduces addition filter options to filter image responses by image size and license type.
TODO
> fix: Bing Image Search - Support to override endpoint url

- package-lock.json
- package.json
- src/common/mockFactory.ts
- src/electron/providers/storage/localFileSystem.test.ts
- src/electron/providers/storage/localFileSystem.ts
- src/providers/activeLearning/electronProxyHandler.test.ts
- src/providers/activeLearning/electronProxyHandler.ts
- src/providers/activeLearning/objectDetection.ts
- src/providers/storage/assetProviderFactory.test.ts
- src/providers/storage/assetProviderFactory.ts
- src/providers/storage/azureBlobStorage.ts
- src/providers/storage/localFileSystemProxy.test.ts
- src/providers/storage/localFileSystemProxy.ts
- src/providers/storage/storageProviderFactory.test.ts
- src/react/components/pages/connections/connectionsPage.tsx
- src/services/assetService.test.ts
- src/services/assetService.ts
All new connections will have a property `relativePath` that will indicate to use a path relative to the source connection when interacting with assets. Old connections will assume absolute path.
Addresses #762
> feat: Use relative paths for local file assets

- src/electron/main.ts
- src/electron/providers/storage/localFileSystem.ts
The electron main process did not register the mixins which was causing recursive file system calls to fail.
> fix: Adds missing registration of mixins to support 'forEachAsync'
