- src/index.js
- src/package.json
- src/public/js/videotagging-ctnk-extension.js
Added cntkEnv configuration
Updated cntk-fastrcnn module to support linux
> Cntk integration patches

- src/index.js
- src/public/js/videotagging-ctnk-extension.js
Added support for generating test images randomly selects 20% of tagged frames as test data
> #92 Added support for auto generation of test images

- src/index.js
- src/lib/detection_algorithms/yolo/exporter.js
- src/public/js/videotagging-ctnk-extension.js
> Version with YOLO exports instead of CNTK

- main.js
- package.json
- src/index.html
- src/index.js
- src/lib/tracking_algorithms/videotagging-tracking-extension.js
- Updated cntk-rcnn-extension
- Added the ability to toggle scene change detection
- Add the ability to enable region copy
> Added Features

- src/bower_components/video-tagging/video-tagging.html
- src/bower_components/video-tagging/video-taggingstyles.html
- src/index.js
- src/main.js
> Image support through video poster

- src/lib/detection_algorithms/yolo/exporter.js
Sometimes, depending on chance, either train.txt or test.txt could start with a newline, which breaks Darknet, as it attempts to load a file called `''`.
So, instead of tracking whether we've started an export at all, track whether we've written anything to these files.
(To be honest, I think an exporter API that didn't use `fs.appendFile` to open-append-close the files would be better, but that would require adding a "finalize" call of some sort.)
This was reported by @moonq.
> YOLO: Ensure files don't start with newlines

- .gitignore
- package-lock.json
- package.json
Fix of potential security vulnerability.
> Update the version of the send npm module

- src/lib/videotagging_extensions/detection.js
Fixed callback causing spinner to exit early
> Fixed loader

- main.js
- src/index.js
- src/lib/detection_algorithms/cntkfastercnn/reviewer.js
- src/lib/videotagging_extensions/detection.js
- Added better error handling for remote active learning removed infinite wait on error.
> Active Learning Bug Fix

- .gitignore
- src/public/css/styles.css
- src/public/js/video-tagging/video-tagging.html
- src/public/js/video-tagging/video-taggingstyles.html
Moved some layout calculations from JS code to CSS (grid based). Some code cleaning after test might be required.
> Update for the aspect ratio/scaling issue

- src/public/js/video-tagging/optional-tags.html
When open from directory with saved file and input some new tags in "load-form-container", those new tags will not have colors.
> Fix the colors for the new tags when open from directory with saved file

- src/public/js/video-tagging/js/canvastools.js
- src/public/js/video-tagging/optional-tags.html
- src/public/js/video-tagging/video-tagging.html
- src/public/js/video-tagging/video-taggingstyles.html
Keyboard shotcuts:
-- Move: ctrl + arrows
-- Resize Up: ctrl+shit + arrows
-- Resize Down: ctrl+alt + arrows
-- Select all - ctrl + a
> Keyboard shortcuts for region move/resize

- src/lib/detection_algorithms/kitti/exporter.js
Fix for no training images being exported due to posFrameIndex only being incremented after label generation but all images are saved before the labels are generated.
> Fix KITTI export missing training images

- src/public/js/video-tagging/video-tagging.html
Fix for seekbar not updating and incorrect frame number being displayed in frame input caused by change in frame id naming
> Fix frame number and seekbar bug from name change

- src/public/js/video-tagging/js/canvastools.js
Fixes conditional check for incorrect element ordering when adding new regions
> Fixes conditional check for incorrect element ordering when adding new regions

- src/index.js
Adds backward compatibility between previous versions of VOTT
> Add back compat functoinality for loading JSON data

- main.js
- package-lock.json
- package.json
- src/index.js
- src/public/js/export-configuration.js
- src/public/js/video-tagging/video-tagging.html
Adds the ability to load and export TFRecord files. *When loading TFRecord, need to provide a label when opening the directory, but VOTT will load the rest of the labels from the records on read. Will resolve #262
> Feature/import export TFRecord files

- src/index.js
- src/public/js/video-tagging/video-tagging.html
Fixes bug where unix systems would save the whole frame path instead of just frame name. Resolves #260
> Fix JSON frame names

- main.js
- src/public/js/video-tagging/js/canvastools.js
- src/public/js/video-tagging/video-tagging.html
Moved the logic to CanvasTools library.
* Added basic invention filter implementation.
* There is now a pipeline of filters based on processing canvases (might be computing resource and memory consuming).
Updated menu in VoTT.
> Moved filters support to canvastools.js

- main.js
- src/public/html/help-configuration.html
- src/public/js/video-tagging/js/canvastools.js
- src/public/js/video-tagging/video-tagging.html
1) Added grayscale filter + fix for resetting filters 
2) Added toggling region box background by Ctrl+b. Updated help on shortcuts.
> 1) Grayscale filter 2) Toggling region background

- package-lock.json
- src/public/js/video-tagging/optional-tags.html
- src/public/js/video-tagging/video-tagging.html
This feature allows the user to add a tag after the initial tag creation in the first window. Now the user can add a tag while in the middle of tagging photos.
> added tag ad-hoc

- package-lock.json
- package.json
- src/react/components/pages/editorPage/editorFooter.test.tsx
- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/editorPage/editorSideBar.test.tsx
- src/react/components/pages/editorPage/editorSideBar.tsx
- src/react/components/pages/projectSettings/projectSettingsPage.tsx
- Integrated react-virtualized component into editor sidebar
- Unit tests on the way
> Integrate virtual scroll component into editor sidebar

- package-lock.json
- src/common/mockFactory.ts
- src/providers/export/vottJson.test.ts
- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/editorPage/editorSideBar.tsx
- src/react/components/pages/export/exportPage.test.tsx
- src/redux/actions/projectActions.ts
- src/redux/reducers/currentProjectReducer.test.ts
- src/redux/reducers/currentProjectReducer.ts
- src/services/assetService.ts
- Not Visited (no change, grey)
- Visited, but not tagged - Display yellow tint
- Tagged - Display Green tint.
> Add styles on editor sidebar based on asset state

- src/index.js
Fixes issue when reading tfrecords after CT update
> Update to work with new canvastools

- .travis.yml
- build/azure-pipelines/linux/continuous-build-linux.yml
- package.json
- src/react/components/common/tagsInput/tagEditorModal/tagEditorModal.tsx
- src/react/components/common/tagsInput/tagsInput.test.tsx
- src/react/components/common/tagsInput/tagsInput.tsx
- src/react/components/pages/appSettings/appSettingsPage.tsx
- src/react/components/pages/connections/connectionForm.tsx
- src/react/components/pages/editorPage/editorFooter.test.tsx
- src/react/components/pages/export/exportForm.tsx
- src/react/components/pages/projectSettings/projectForm.tsx
- changed JSON file imports to use require
- updated build definitions to run tsc as part of build
> Fixed tsc compile errors from JSON files

- src/react/components/pages/editorPage/editorSideBar.test.tsx
- src/react/components/pages/editorPage/editorSideBar.tsx
- Updated editor sidebar component to fire select event handler on prop change
> Fixes issue with testing editor sidebar selection

- src/index.scss
- src/react/components/common/connectionPicker.tsx
- src/react/components/common/customField.tsx
- src/react/components/common/customFieldTemplate.tsx
- src/react/components/pages/connections/connectionForm.json
- src/react/components/pages/connections/connectionForm.tsx
- src/react/components/pages/connections/connectionsPage.tsx
- src/react/components/pages/export/exportForm.tsx
- src/react/components/pages/export/exportPage.test.tsx
- src/react/components/pages/export/exportPage.tsx
- src/react/components/pages/projectSettings/projectForm.json
- src/react/components/pages/projectSettings/projectForm.test.tsx
- src/react/components/pages/projectSettings/projectForm.tsx
- src/react/components/pages/projectSettings/projectSettingsPage.tsx
- src/redux/reducers/currentProjectReducer.ts
- Cleaned up form to use bootstrap v4 validation styling
- Added custom validation logic
- Added cancel button
- Added custom submit button
> Global Form UI Cleanup

- package-lock.json
- package.json
- src/react/components/common/tagsInput/tagEditorModal/tagEditorModal.test.tsx
- src/react/components/common/tagsInput/tagEditorModal/tagEditorModal.tsx
- src/react/components/common/tagsInput/tagsInput.test.tsx
- src/react/components/common/tagsInput/tagsInput.tsx
- src/react/components/pages/editorPage/editorFooter.test.tsx
- Replace old modal with reactstrap modal
- Fix unit tests to reflect change
- Add bug fix in Tags Input to prevent modal from changing tags to empty names
> Replace old modal with Reactstrap Modal

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- Add template for bug report and feature request
> Update issue templates for master branch

- src/react/components/common/condensedList/condensedList.scss
Fixes issue with relative file location for condensedList.sass
> fix file location issue

- package-lock.json
- package.json
- src/react/components/common/confirm.tsx
- src/react/components/common/confirm/confirm.test.tsx
- src/react/components/common/confirm/confirm.tsx
- src/react/components/common/tagsInput/tagEditorModal/tagEditorModal.tsx
- src/react/components/pages/connections/connectionsPage.test.tsx
- src/react/components/pages/connections/connectionsPage.tsx
- src/react/components/pages/homepage/homePage.test.tsx
- src/react/components/pages/homepage/homePage.tsx
- src/react/components/pages/homepage/recentProjectItem.tsx
- Added confirm component
- Integrated confirmation in homepage and connections listing
Test pending
> Added basic confirmation component

- src/react/components/common/alert/alert.test.tsx
- src/react/components/common/confirm/confirm.test.tsx
- src/react/components/common/messageBox/messageBox.test.tsx
- Forced update when modal is opened
- Removed DOM querySelector method calls
> Refactored tests to use enzyme methods vs. direct DOM methods

- src/react/components/common/tagsInput/tagsInput.scss
- src/react/components/common/tagsInput/tagsInput.test.tsx
- src/react/components/common/tagsInput/tagsInput.tsx
- src/react/components/pages/editorPage/editorFooter.test.tsx
- src/react/components/pages/editorPage/editorPage.scss
> Updated CSS styling for tags component

- src/common/mockFactory.ts
- src/common/strings.test.ts
- src/providers/storage/assetProvider.test.ts
- src/providers/storage/assetProvider.ts
- src/providers/storage/storageProvider.test.ts
- src/providers/storage/storageProvider.ts
- src/react/components/common/connectionProviderPicker/connectionProviderPicker.test.tsx
- src/react/components/common/connectionProviderPicker/connectionProviderPicker.tsx
- src/react/components/pages/connections/connectionForm.json
- src/react/components/pages/connections/connectionForm.tsx
- src/react/components/pages/connections/connectionForm.ui.json
- src/react/components/pages/connections/connectionsPage.test.tsx
- src/registerProviders.ts
- Created connection provider picker component
- Unit tests (pending)
> Created connection provider picker to dynamically load provider list

- package-lock.json
- src/react/components/pages/editorPage/editorPage.scss
> Lumirand css fix AB#16414 AB#16444

- src/registerProviders.ts
My merge accidently replaced the custom vision provider with a copy of the pascal one.
> Fixing broken merge

- src/common/mockFactory.ts
- src/providers/storage/azureBlobStorage.test.ts
- As part of effort to add JSDocs throughout application
- Made a few renaming changes, no functionality changes
> Clean up and document mock factory

- .env.test
- package.json
- src/common/hostProcess.test.ts
- src/common/hostProcess.ts
- src/providers/storage/assetProviderFactory.ts
- src/providers/storage/storageProviderFactory.ts
- src/registerProviders.test.ts
- Refactored host process to not run inline
- Added unit tests for host process
- Updated test scripts due to jest plugin debug breakage
> Host Process Unit Tests

- src/App.tsx
- src/services/assetService.ts
- src/services/connectionService.ts
- src/services/projectService.ts
- JSDocs for src/services directory
- JSDocs for src directory
> JSDocs for src/services and src directories

- package-lock.json
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/mockFactory.ts
- src/common/strings.test.ts
- src/common/strings.ts
- src/models/applicationState.ts
- src/providers/export/exportProviderFactory.test.ts
- src/react/components/pages/projectSettings/projectForm.json
- src/react/components/pages/projectSettings/projectForm.test.tsx
- src/react/components/pages/projectSettings/projectForm.tsx
- Adding video settings to project page
- Adding tests for video settings
- Adding default value for video settings and validating it with test
- Mocking video settings for tests
- Storing video settings within project
> Video Settings added to project settings page AB#16627

- src/common/crypto.test.ts
- src/common/crypto.ts
- Fixes issue where 1 unit test randomly fails
> Fix crypto random test failure

- src/common/mockFactory.ts
- src/react/components/pages/homepage/homePage.test.tsx
- src/react/components/pages/homepage/homePage.tsx
- Added overload to mock factory flushUi that doesn't require func
- Added new test to verify loadProject method is successfully called after valid project file upload.
> Homepage verify project upload test

- package-lock.json
- src/electron/providers/storage/localFileSystem.ts
- src/providers/storage/localFileSystemProxy.test.ts
- src/providers/storage/localFileSystemProxy.ts
- src/react/components/pages/editorPage/assetPreview.tsx
**WIP, do not review yet. Need to test yet on Windows**
> Standardize on POSIX Slash path separator and use Path.resolve() to support Windows convertion at runtime

- src/App.tsx
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/models/applicationState.ts
- src/react/components/common/errorBoundary.test.tsx
- src/react/components/common/errorBoundary.tsx
- src/react/components/pages/homepage/homePage.test.tsx
- src/react/components/pages/homepage/homePage.tsx
- src/redux/actions/appErrorActions.ts
also add an example on how to use the global error redux
for caught exception.
> [AB#16670] add ErrorBoundary to top level app to catch render exception

- src/App.tsx
this broke navigation render, settings doesn't load until
refresh
> move errorBoundary outside Router

- src/services/projectService.test.ts
- src/services/projectService.ts
> Fix issue with saving project files

- src/common/mockFactory.ts
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/toolbar/copyRectangle.test.tsx
- src/react/components/toolbar/copyRectangle.tsx
- src/registerToolbar.ts
Fixes bug where polygon was saved as rectangle on editor page
> Fix shape save issue after toolbar refactor

- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.tsx
> Updated editor/canvas CSS to take up full screen real estate

- package-lock.json
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/editorPage.scss
-Simplified positioning to use CSS classes vs. JS style manipulation
-Updated set canvas sort to work on seeking
-Refactor to support async methods.
> Updated CSS for video/canvas positioning

- src/App.tsx
- src/react/components/common/keyboardBinding/keyboardBinding.test.tsx
- src/react/components/common/keyboardBinding/keyboardBinding.tsx
- src/react/components/common/keyboardManager/keyboardManager.test.tsx
- src/react/components/common/keyboardManager/keyboardManager.tsx
- src/react/components/common/keyboardManager/keyboardRegistrationManager.test.ts
- src/react/components/common/keyboardManager/keyboardRegistrationManager.ts
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/editorPage/editorToolbar.test.tsx
- src/react/components/pages/editorPage/editorToolbar.tsx
- src/react/components/toolbar/nextAsset.tsx
- src/react/components/toolbar/previousAsset.tsx
- src/react/components/toolbar/toolbarItem.test.tsx
- src/react/components/toolbar/toolbarItem.tsx
- src/registerToolbar.ts
- src/services/assetService.ts
Allows a single place to register keyboard events across the application.  Automatically registers and deregisters event handlers as keyboard bindings go int/out of scope.
- New `KeyboardManager` component (top level context component)
- New `KeyboardBinding` component (Allows keyboard bindings within pages / components)
> Keyboard Manager Component

- package.json
- src/electron/main.ts
- src/react/components/common/keyboardManager/keyboardRegistrationManager.ts
- Reved package to 2.0.0-preview.1
- Don't open dev tools by default
- Fixed minor guard bug in keyboard manager
> Reved package version and fixed minor bugs

- package.json
- src/react/components/common/keyboardBinding/keyboardBinding.test.tsx
- src/react/components/common/keyboardBinding/keyboardBinding.tsx
- src/react/components/common/keyboardManager/keyboardManager.test.tsx
- src/react/components/common/keyboardManager/keyboardManager.tsx
- src/react/components/common/keyboardManager/keyboardRegistrationManager.test.ts
- src/react/components/common/keyboardManager/keyboardRegistrationManager.ts
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/toolbar/toolbarItem.tsx
- Still needs test, opening up to get feedback on approach
- Removed unused keydown package
> Add support for keyUp and keyPress events

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/providers/export/azureCustomVision.json
- src/providers/export/azureCustomVision.ts
- src/providers/export/tensorFlowPascalVOC.json
- src/providers/export/tensorFlowRecords.json
- src/providers/export/vottJson.json
- src/registerProviders.ts
- Localized all export project JSON files
> Added localization for export JSON files AB#16387

- src/common/mockFactory.ts
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/redux/reducers/currentProjectReducer.test.ts
- src/redux/reducers/currentProjectReducer.ts
- src/services/assetService.test.ts
- src/services/assetService.ts
- When you edit a connection settings while having a project loaded it will update the project to use the updated connection settings
- Optimized data stored in project / asset files
> Update project when in-use connection changes AB#16921

- package-lock.json
- src/react/components/common/assetPreview/videoAsset.tsx
- src/react/components/common/keyboardBinding/keyboardBinding.test.tsx
- src/react/components/common/keyboardBinding/keyboardBinding.tsx
- src/react/components/common/keyboardManager/keyboardRegistrationManager.test.ts
- src/react/components/common/keyboardManager/keyboardRegistrationManager.ts
- src/react/components/common/videoPlayer/customVideoPlayerButton.test.tsx
- src/react/components/common/videoPlayer/customVideoPlayerButton.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/toolbar/toolbarItem.test.tsx
- src/react/components/toolbar/toolbarItem.tsx
- src/registerToolbar.ts
1. replace toolbar left/right button with up/down buttons
to match keyboard
1. add support for up/down & w/s key for moving between assets
1. support multiple accelerators per binding
> [Fixes AB#16951] - support up/down & w/s key for navigating assets

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/models/applicationState.ts
- src/react/components/pages/homepage/homePage.test.tsx
- src/react/components/pages/homepage/homePage.tsx
- src/react/components/pages/projectSettings/projectSettingsPage.tsx
- src/redux/actions/projectActions.test.ts
- src/redux/actions/projectActions.ts
- Fixes issue deleting project
Issue: After security tokens were introduced the storage provider was not able to be instantiated because it was attempting to load the provider from the encrypted provider settings.
> Fixed delete project bug AB#17024

- package-lock.json
- package.json
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/editorPage.test.tsx
Updates vott-ct library and updates tests
> Update canvastools and fix tests

- src/index.scss
- src/react/components/common/common.scss
- src/react/components/common/customField/customFieldTemplate.test.tsx
- src/react/components/common/customField/customFieldTemplate.tsx
Fixes issue where validation messages weren't showing for source/target connection errors in project settings page.
> Fixed field validation bug AB#17057

- src/electron/main.ts
- Adds right-click context menu options for all input elements in electron app
> Added context menu option in electron for all input fields AB#16922

- package-lock.json
- src/react/components/pages/editorPage/editorSideBar.test.tsx
- src/react/components/pages/editorPage/editorSideBar.tsx
Sidebar is not updated when moving between asset with tool bar button or keyboard button.  Update to always focus on selected asset on first asset on first load.
> Fixes [AB#17029] fix sidebar so it's in sync with asset navigation

- src/react/components/common/assetPreview/assetPreview.test.tsx
- src/react/components/common/assetPreview/assetPreview.tsx
- src/react/components/common/assetPreview/imageAsset.test.tsx
- src/react/components/common/assetPreview/imageAsset.tsx
- src/react/components/common/assetPreview/videoAsset.test.tsx
- src/react/components/common/assetPreview/videoAsset.tsx
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/editorPage/editorSideBar.tsx
- src/services/assetService.test.ts
- src/services/assetService.ts
Corrects the issue where the assets viewed inside VoTT are not always displayed in the correct aspect ratio, regions are skewed and region scaling does not work 100%.  Also corrects issue with resizing assets while resizing the main application window.
Resolves AB#17073
> fix: Corrects canvas sizing and region sizes

- src/common/htmlFileReader.ts
- src/providers/export/azureCustomVision.ts
- src/providers/export/exportProvider.test.ts
- src/providers/export/exportProvider.ts
- src/providers/export/vottJson.ts
- src/react/components/common/assetPreview/videoAsset.tsx
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/react/components/pages/editorPage/editorPage.tsx
Fixes failing tests in Phi's export video branch
> Fix failing tests in export video branch

- src/common/array.ts
- src/common/htmlFileReader.ts
- src/common/map.ts
- src/index.tsx
- src/providers/export/azureCustomVision.test.ts
- src/providers/export/azureCustomVision.ts
- src/providers/export/exportProvider.test.ts
- src/providers/export/exportProvider.ts
- src/providers/export/tensorFlowPascalVOC.test.ts
- src/providers/export/tensorFlowPascalVOC.ts
- src/providers/export/tensorFlowRecords.test.ts
- src/providers/export/tensorFlowRecords.ts
- src/providers/export/vottJson.test.ts
- src/providers/export/vottJson.ts
- src/registerMixins.ts
Adds support for processing/batching array operations in parallel.
> (WIP)feature:Add support for async forEach/map

- .sonarcloud.properties
1. we were getting code smell noise on test files
1. team has decide to ignore these analysis
> ci: update sonarcloud to ignore test files

- package-lock.json
- src/react/components/common/connectionPicker/connectionPicker.test.tsx
- src/react/components/common/connectionPicker/connectionPicker.tsx
- src/react/components/pages/projectSettings/projectForm.test.tsx
- src/react/components/pages/projectSettings/projectForm.tsx
This fixes the issue where the "Add Connection" button currently displays with the incorrect styles making it appear that the button is disabled.
Resolves AB#17158
> fix:Add Connection button displays with correct style

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/mockFactory.ts
- src/common/strings.ts
- src/models/applicationState.ts
- src/providers/export/azureCustomVision.test.ts
- src/providers/export/tensorFlowPascalVOC.test.ts
- src/providers/export/tensorFlowRecords.test.ts
- src/providers/export/vottJson.test.ts
- src/react/components/pages/appSettings/appSettingsPage.tsx
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/editorPage.test.tsx
- src/redux/actions/projectActions.test.ts
- src/redux/actions/projectActions.ts
- src/redux/reducers/currentProjectReducer.test.ts
- src/services/assetService.test.ts
- src/services/assetService.ts
- Add Project version to project file
- Add Project version to asset metadata file
- Show Project version in App Settings Page
Implement [#AB17100]
> feat: Add Project version info

- electron-builder.yml
- package-lock.json
- package.json
Update release package names to use a more standard convention
that includes version. Add more details to `package.json`.
AB#17236
> ci: update release names and package details

- package-lock.json
- src/common/crypto.ts
- src/common/guard.test.ts
- src/common/guard.ts
- src/providers/export/azureCustomVision/azureCustomVisionService.ts
- src/providers/export/exportProviderFactory.ts
- src/providers/storage/assetProviderFactory.ts
- src/providers/storage/storageProviderFactory.ts
- src/react/components/common/keyboardManager/keyboardRegistrationManager.test.ts
- src/services/assetService.ts
This PR fixes one oddly pervasive typo.
AB#17326
> fix: replaces emtpy with empty throughout

- README.md
This PR adds a list to the user docs of all keyboard shortcuts currently implemented in the app.
AB#17123
> docs: adds list of shortcuts (hotkeys) to docs

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/models/applicationState.ts
- src/providers/export/exportProviderFactory.ts
- src/redux/actions/projectActions.test.ts
- src/redux/actions/projectActions.ts
export wasn't doing anything because there wasn't a default format.
AB#17437
> fix: set default export format in project

- azure-pipelines/web/deploy-to-azure-dev.yml
- azure-pipelines/web/deploy-to-azure-v2.yml
Yaml files to deploy VoTT to Azure when PRs are merged into
`dev` and `v2` branches.
[AB#17489](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=17489)
> ci: Azure DevOps pipeline definitions for VoTT Web CD

- azure-pipelines/web/deploy-to-azure-dev.yml
- azure-pipelines/web/deploy-to-azure-v2.yml
only deploy on merge to `dev` and `v2`
AB#17541
> ci: disable web vott deploy for PR

- src/providers/export/azureCustomVision.json
- src/providers/export/tensorFlowPascalVOC.json
- src/providers/export/tensorFlowRecords.json
- src/providers/export/vottJson.json
- src/react/components/pages/export/exportForm.test.tsx
- src/react/components/pages/export/exportForm.tsx
> fix: standardize default export option to "visited"

- src/react/components/pages/projectSettings/projectMetrics.test.tsx
- src/react/components/pages/projectSettings/projectMetrics.tsx
- src/react/components/pages/projectSettings/projectSettingsPage.scss
> fix: display spinner icon on metrics panel when loading

- src/App.tsx
- src/react/components/shell/sidebar.test.tsx
- src/react/components/shell/sidebar.tsx
Remove all unimplemented icons from view. This fix keeps any functionality required to add these features in the future.
> fix: remove profile settings and active learning

- src/react/components/pages/editorPage/editorPage.tsx
- src/services/assetService.test.ts
- src/services/assetService.ts
- fix: open file containing pound character in the name 
Fix [AB#17533]
> fix: open file containing pound character in the name [AB#17533]

- src/react/components/pages/editorPage/editorFooter.tsx
Tried to add the fix in` vott-react`, but it didn't work. This Fixes [AB#17358] and [AB#17352]
> fix: Blurring tag input on click and change

- src/App.scss
- src/react/components/common/condensedList/condensedList.scss
- src/react/components/pages/appSettings/appSettingsPage.scss
- src/react/components/pages/connections/connectionsPage.scss
- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/homepage/homePage.scss
- src/react/components/pages/projectSettings/projectMetrics.tsx
- src/react/components/pages/projectSettings/projectSettingsPage.scss
- src/react/components/shell/statusBar.scss
- src/react/components/shell/titleBar.scss
- src/react/components/shell/titleBar.tsx
Resolves some overflow flexbox issues where the flexbox heights are not extending to the height of the scrolling app-content container.
Resolves AB#16458
> fix: Cleans up some of the flexbox styling overflow content heights

- azure-pipelines.yml
- azure-pipelines/web/deploy-to-azure-dev.yml
- trigger CI build for all PR targeting `dev*`
- trigger web deploy build on merge to all branches with prefix `dev`
> ci: update pipelines to work for all branches with prefix dev

- src/assets/sass/theme.scss
- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorSideBar.tsx
Reducing the size of the Editor Page Sidebar to give more screen area to the asset currently being tagged. First part of Sidebar restyling.
[AB#17652](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=17652)
> WIP: resizes thumbnails and sidebar

- src/common/mockFactory.ts
- src/models/applicationState.ts
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/projectSettings/projectForm.json
- src/services/importService.ts
Adds auto-labeling and auto-tagging active learning settings/features to app and puts settings in project settings page.
*Still needs tests
> (WIP) feat: Add auto-labeling and auto-tagging active learning settings/features

- azure-pipelines/plato/generate-up-to-date-report.yml
- azure-pipelines/releases/README.md
- azure-pipelines/releases/VoTT - Upload Plato Report.json
- scripts/update-report.sh
1. replace `az storage` command with `az copy` task for uploading
1. templatize pipeline
[AB#17780](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=17780)
Generate report (build) => Upload (release)
https://dev.azure.com/msft-vott/VoTT/_build/results?buildId=1961 => https://dev.azure.com/msft-vott/VoTT/_releaseProgress?_a=release-environment-logs&releaseId=167&environmentId=167
> ci: refactor plato report pipeline

- src/App.scss
- src/App.tsx
- src/common/mockFactory.ts
- src/react/components/common/assetPreview/assetPreview.test.tsx
- src/react/components/common/assetPreview/tfrecordAsset.test.tsx
- src/react/components/common/assetPreview/tfrecordAsset.tsx
- src/react/components/pages/editorPage/editorPage.test.tsx
Fixes bug where tfrecords show error loading image
Resolves [AB#17680](https://dev.azure.com/dwrdev/web/wi.aspx?pcguid=80f9922c-b416-454c-92c6-ab7b6867e0b2&id=17680)
> fix: Catch error while tfrecord image not loaded

- azure-pipelines/linux/artifact-build-linux.yml
- azure-pipelines/mac/artifact-build-mac.yml
- azure-pipelines/windows/artifact-build-windows.yml
- package-lock.json
- package.json
- public/index.html
- scripts/build.sh
- scripts/release-pr.sh
- src/index.scss
- src/react/components/pages/appSettings/appSettingsPage.tsx
- src/react/components/pages/homepage/homePage.tsx
Remove electron functionality from browser builds. Some updates to
CI scripts, based on things found in the last release.
> feat: exclude desktop functionality from browser target

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/react/components/pages/connections/connectionsPage.test.tsx
- src/react/components/pages/connections/connectionsPage.tsx
- src/react/components/pages/homepage/homePage.test.tsx
- src/react/components/pages/homepage/homePage.tsx
Re-adds toast messages during connection create/delete as well as homepage recent project delete.
> feat: Add toast messages when entities are created / deleted

- src/react/components/common/assetPreview/assetPreview.tsx
- src/react/components/common/assetPreview/imageAsset.tsx
- src/react/components/common/assetPreview/tfrecordAsset.tsx
- src/react/components/common/assetPreview/videoAsset.test.tsx
- src/react/components/common/assetPreview/videoAsset.tsx
- src/react/components/common/common.scss
- src/react/components/common/tagInput/tagInput.scss
- src/react/components/pages/editorPage/canvas.test.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.tsx
- src/redux/reducers/currentProjectReducer.test.ts
- src/redux/reducers/currentProjectReducer.ts
- Simplifies asset loading flow across images and video assets to be more deterministic and testable
> fix: Simplifies asset load flow

- src/common/mockFactory.ts
- src/providers/export/azureCustomVision.test.ts
- src/react/components/pages/homepage/homePage.tsx
- src/services/assetService.test.ts
- src/services/assetService.ts
- src/services/importService.test.tsx
- src/services/importService.ts
- Normalizes and simplifies v1 project import
- Paths are now normalized in 1 place when the asset is initially created.
> fix: Refactor and normalize v1 project import

- CODE_OF_CONDUCT.md
- Adds project code of conduct
> doc: Code of Conduct

- src/index.scss
Hi!
I saw this issue in the code and wasn't sure if was intentional or not, but opened a PR to help
> fix: remove duplicated border-radius CSS

- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/editorPage/editorSideBar.test.tsx
- src/react/components/pages/editorPage/editorSideBar.tsx
> Revert "feat: move asset preview to horizontal"

- azure-pipelines/templates/build-artifact.yml
- azure-pipelines/templates/create-github-release.yml
- preview-release-pipeline.yml
- scripts/version-bump-commit.sh
> chore: pipeline for preview release (queue manually)

- .dependabot/config.yml
Dependabot will check for dependencies update weekly
> chore: install dependabot

- src/react/components/pages/editorPage/editorSideBar.tsx
> fix: sidebar not showing thumbnails
